version: '3'
services:
  api:
    image: "triggerflow/trigger-api:latest"
    environment:
      - TRIGGERFLOW_CONTROLLER_ENDPOINT=controller:5000
      - TRIGGERFLOW_STORAGE_BACKEND=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=123456
      - CREATE_ADMIN_USER=yes
    ports:
      - "8080:8080"
    depends_on:
      - "redis"
  controller:
    build:
      context: ../../
      dockerfile: deploy/standalone/Dockerfile
    depends_on:
      - "redis"
  redis:
    image: "redis:6.0.5-buster"
    command: ["--requirepass", "123456"]
    ports:
      - "6379:6379"
  kafka:
    image: "lensesio/fast-data-dev:2.2"
    ports:
      - "3030:3030"
      - "9092:9092"
  rabbit:
    image: "rabbitmq:3.8.5-management"
    ports:
      - "5671-5672:5671-5672"
      - "15672:15672"
